<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Confirm</strong> Action' => 'تأكيد الإجراء',
    '<strong>Mail</strong> summary' => 'ملخص البريد',
    'Add:' => 'إضافة:',
    'An error occurred while handling your last action. (Handler not found).' => '',
    'An unexpected error occurred while loading the search result.' => '',
    'An unexpected error occurred. If this keeps happening, please contact a site administrator.' => '',
    'An unexpected server error occurred. If this keeps happening, please contact a site administrator.' => '',
    'An unknown error occurred while uploading.' => '',
    'An unknown error occurred while uploading. Hint: check your upload_max_filesize and post_max_size php settings.' => '',
    'Confirm' => 'تأكيد',
    'Copy to clipboard' => 'نسخ إلى الحافظة',
    'Could not find requested page.' => 'تعذر العثور على الصفحة المطلوبة',
    'Delete' => 'حذف',
    'Do you really want to perform this action?' => 'هل تريد حقًا القيام بهذا الإجراء؟',
    'Edit' => 'تحرير',
    'Error while running your last action (Invalid request method).' => '',
    'Error:' => 'خطأ:',
    'Export' => 'تصدير',
    'Info:' => 'تصدير',
    'Invalid request method!' => 'طريقة الطلب غير صالحة!',
    'Loading...' => 'جارٍ التحميل ...',
    'Logo of {appName}' => '{appName}شعار',
    'My profile image' => 'صورة ملفي الشخصي',
    'No error information given.' => 'لم يتم تقديم معلومات خطأ',
    'Open' => 'فتح',
    'Please type at least {count} characters' => 'الرجاء كتابة {count} حرفًا على الأقل',
    'Profile dropdown' => 'القائمة المنسدلة للملف الشخصي',
    'Profile image of {displayName}' => '{displayName}صورة الملف الشخصي لـ ',
    'Profile picture of {displayName}' => '{displayName}صورة الملف الشخصي لـ ',
    'Select Me' => 'اخترني',
    'Show less' => 'إظهار أقل',
    'Some files could not be uploaded:' => 'تعذر تحميل بعض الملفات: ',
    'Text could not be copied to clipboard' => 'تعذر نسخ النص إلى الحافظة',
    'Text has been copied to clipboard' => 'تم نسخ النص إلى الحافظة',
    'The file has been deleted.' => 'تم حذف الملف',
    'The requested resource could not be found.' => 'تعذر العثور على المورد المطلوب.',
    'The space has been archived.' => 'تم وضع المساحة في الأرشيف',
    'The space has been unarchived.' => 'تمت إزالة المساحة من الأرشيف',
    'Time Zone' => 'المنطقة الزمنية',
    'Toggle comment menu' => 'تبديل قائمة التعليقات',
    'Toggle panel menu' => 'تبديل قائمة اللوحة',
    'Toggle post menu' => 'تبديل قائمة النشر',
    'Toggle stream entry menu' => 'تبديل قائمة دخول لوحة القيادة',
    'Upload' => 'تحميل',
    'Upload file' => 'تحميل ملف',
    'You are not allowed to run this action.' => 'غير مسموح لك بتشغيل هذا الإجراء.',
    '<strong>Latest</strong> updates' => '<strong>آخر</strong> التحديثات',
    'Account settings' => 'إعدادات الحساب',
    'Administration' => 'الإدارة',
    'Allow' => 'السماح',
    'Back' => 'عودة',
    'Back to dashboard' => 'عودة لسطح المكتب',
    'Cancel' => 'إلغاء',
    'Choose language:' => 'خيارات اللغه:',
    'Close' => 'اغلاق',
    'Collapse' => 'إغلاق',
    'Content Addon source must be instance of HActiveRecordContent or HActiveRecordContentAddon!' => 'محتوى الإضافة لابد أن يكون موجود في HActiveRecordContent أو HActiveRecordContentAddon',
    'Could not find content of addon!' => 'لم يمكن ايجاد محتويات الإضافة',
    'Default' => 'الإفتراضي',
    'Deny' => 'رفض',
    'Error' => 'خطأ',
    'Expand' => 'توسعة',
    'It looks like you may have taken the wrong turn.' => 'يبدو انك أتيت للصفحة الخطأ',
    'Language' => 'اللغة',
    'Login' => 'تسجيل الدخول',
    'Logout' => 'تسجيل الخروج',
    'Menu' => 'القائمة',
    'Module is not enabled on this content container!' => 'الموديل ليس متاحاً في هذه الخانة',
    'My profile' => 'صفحتي الشخصية',
    'New profile image' => 'صورة شخصية جديدة',
    'Next' => 'التالي',
    'Oooops...' => 'يالهوي...',
    'Please type at least 3 characters' => 'الرجاء كتابة آخر 3 حروف',
    'Save' => 'حفظ',
    'Saved' => 'تم الحفظ',
    'Search' => 'بحث',
    'Show more' => 'مشاهدة المزيد',
    'The date has to be in the past.' => 'التاريخ يبدوا أنه من الماضي',
    'Unsubscribe' => 'ألغ الإشتراك',
];
